# Generated by Django 5.0 on 2024-01-06 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='images',
            field=models.ImageField(default='blog/default.jpg', upload_to='blog/'),
        ),
    ]
