# Generated by Django 5.0 on 2023-12-29 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='created_at',
            new_name='created_date',
        ),
    ]
