# Generated by Django 5.0 on 2024-01-05 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_rename_created_at_portfolio_created_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={'ordering': ('created_date',)},
        ),
    ]
