# Generated by Django 5.0 on 2024-01-08 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_portfolio_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='portfolio/'),
        ),
    ]
